site_name: ICBO
site_url: https://github.com/ICBO-conference/icbo2025
site_author: International Conference on Biomedical Ontology
site_description: "International Conference on Biomedical Ontology ICBO"
repo_url: https://github.com/ICBO-conference/icbo2025
#edit_uri: edit/main/docs/
copyright: "Cinder template is licensed under the <a href='https://github.com/erfelipe2/icbotest/blob/master/LICENSE.md'>MIT license</a>"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true
  disable_nav_previous_next: true


nav:
  - Home: index.md
  - Program: program.md
  - Register: registration.md
  - Organizers: co-organizers.md
  # - Travel: travel.md
  # - Example 1: example1.md
  # - Example 2: example2.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
